# Must be an absolute path to db (no ~/) (required)
db_path = "/home/parachain/.local/share/polkadot/chains/dev/db"

# How much should the read-only database keep in cache (MB) (default: 128)
cache_size = 128

# Number of threads to dedicate for executing blocks
# Optional. If not specified, threads will be set
# to the default number of logical system threads
block_workers = 4
# Number of 64KB Heap Pages to allocate for WASM execution default: 2048
wasm_pages = 512

# Optional Database Parameters. 
# Can also be specified via the `DATABASE_URL` environment variable

# Can also be specified with DB_HOST environment variable
db_host = "localhost"
# Can also be specified with DB_PORT environment variable
 db_port = "5432"
# Can also be specified with DB_USER environment variable
db_user = "postgres"
# Can also be specified with DB_PASS environment variable
db_pass = "123"
# Can also be specified with DB_NAME environment variable
db_name = "polkadot_db"


[[kafka]]
url = "localhost:9092"
topic = "polkadot-storage"
key="0"
mode = "plain"
username = "aaa"
password = "kkk"

[[kafka]]
url = "localhost:9092"
topic = "kusama-storage"
key="0"
mode = "plain"
username = "aaa"
password = "kkk"
